### ISSUE TITLE
Open Graph protocol meta tags

### ISSUE THREAD

**Issue by Zalitoar** [ign-argentina/argenmap#95]
Add the meta tags defined by the [https://ogp.me/](Open Graph protocol)

- [x] og:title - The title of your object as it should appear within the graph, e.g., "Argenmap".
- [x] og:image - An image URL which should represent your object within the graph.
- [x] og:url - The canonical URL of your object that will be used as its permanent ID in the graph, e.g., "https://mapa.ign.gob.ar/" Could it be defined by parameter?
- [x] og:description - "Visualizador de mapas" Could it be defined by parameter?
